name: immunbert
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - biopython
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
    - torch>=1.9.0
    - torchvision
    - torchaudio
    - proteinmpnn
    - pandora-package
    - masif